# Generated by Django 3.1.1 on 2021-02-06 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('level_number', models.IntegerField(unique=True)),
                ('answer', models.CharField(blank=True, max_length=256, null=True)),
                ('link', models.URLField()),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField(unique=True)),
                ('one_time_code', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
