# Generated by Django 3.1.1 on 2021-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210206_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
