# Generated by Django 3.1.1 on 2021-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='one_time_code',
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
