# Generated by Django 3.1.1 on 2021-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210208_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
