# Generated by Django 3.1.1 on 2021-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210208_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_year',
            field=models.BooleanField(default=False),
        ),
    ]
