# Generated by Django 3.1.1 on 2021-02-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_first_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finish',
            field=models.BooleanField(default=False),
        ),
    ]
