# Generated by Django 3.1.1 on 2021-02-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210210_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finish',
            field=models.IntegerField(default=0),
        ),
    ]
