# Generated by Django 3.1.1 on 2021-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_level_decay'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attemp_time_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
