# Generated by Django 3.1.1 on 2021-02-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_student_banned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='attemp_time_stamp',
            new_name='attempt_time_stamp',
        ),
    ]
